# Site settings
title: Camila Bisio
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Camila Bisio
user_description: I'm a Software Engineer 
user_title: Software Engineer
email: camibisiob@hotmail.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: camila-bisio
github_username:  cbisio
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum
spotify_username: camila6

exclude: ['package.json', 'src' , 'node_modules']
